#!/usr/bin/env python3
"""
Filter RNAcentral GFF3 to produce a non-redundant, predicted-gene-aware set.

Strategy:

Step 0 – Drop circRNA
  circRNA entries are excluded outright, before any other filtering. RNA
  Framework's fold/norm steps and STAR/Bowtie mapping assume a linear
  transcript; CIRCpedia/circAtlas coordinates only give the genomic span of
  the backsplice loop, not a real circular topology, so these aren't valid
  structure-probing targets without junction-aware mapping and folding.

Pre-filter
  Require at least one authoritative database per biotype (e.g. miRBase for
  miRNA). Keep only primary chromosomes. RFAM-only entries whose sequences
  match the Rfam seed alignments are always kept regardless of the
  authoritative DB check (RFAM_SEED_ALLOWLIST).
  lncRNA: added refseq as authoritative. rRNA/snRNA/misc_RNA: added pdbe.

Stage 1 – Per-URS deduplication
  The same RNA sequence (URS base ID, e.g. URS00008C39CF_9606) can appear
  multiple times at the same locus, once per providing database (.16, .17 …).
  Collapse to the single best representative by DB_PRIORITY rank of the
  providing_databases field. Copies at different loci are kept.

Stage 2 – Predicted-gene-aware locus filtering
  After Stage 1 each URS has at most one entry per locus. Group remaining
  transcripts into overlap clusters by (chrom, strand, type).  Within each
  cluster, prefer transcripts whose Parent points to an actual predicted_gene
  feature.  If predicted-gene-backed transcripts exist, group candidates by
  predicted_gene parent and keep exactly one representative per parent.  In
  addition, any transcript with more than 5 unique database hits is always
  kept regardless of ranking.  If no predicted_gene-backed transcripts exist
  in the cluster, keep one best representative for the whole cluster.
  Representatives are chosen by:
    1. Best (lowest) effective DB_PRIORITY rank  (providing_databases, then
       databases as fallback)
    2. Most unique databases  (broadest support)
    3. Longest transcript
    4. Lexicographic ID  (determinism)

Usage:
  python filter_rnacentral_gff3.py [--no-prefilter] [--pirna-max-loci N] input.gff3[.gz] output.gff3[.gz]

  --no-prefilter skips the authoritative-DB check, for organisms whose primary
  source (SGD, Ensembl Plants, Rfam) is not on the per-biotype lists.
  --pirna-max-loci N drops piRNA sequences mapped to more than N genomic loci
  (repeat-derived; reads multimap and nothing can be measured per locus).
"""

import gzip
import re
import sys
from collections import defaultdict

DB_PRIORITY: list[str] = [
    "mirbase",           # 0
    "wormbase",          # 1
    "hgnc",              # 2
    "gencode",           # 3
    "ensembl",           # 4
    "tair",              # 5
    "sgd",               # 6
    "flybase",           # 7
    "dictybase",         # 8
    "pombase",           # 9
    "mgi",               # 10
    "rgd",               # 11
    "zfin",              # 12
    "mirgenedb",         # 13
    "plncdb",            # 14
    "lncipedia",         # 15
    "lncrnadb",          # 16
    "lncbook",           # 17
    "gtrnadb",           # 18
    "tmrna website",     # 19
    "5srrnadb",          # 20
    "ribocentredb",      # 21
    "pdbe",              # 22
    "refseq",            # 23
    "ensembl plants",    # 24
    "ensembl metazoa",   # 25
    "ensembl protists",  # 26
    "ensembl fungi",     # 27
    "genecards",         # 28
    "malacards",         # 29
    "intact",            # 30
    "expression atlas",  # 31
    "rfam",              # 32
    "tarbase",           # 33
    "lncbase",           # 34
    "snodb",             # 35
    "snorna database",   # 36
    "pirbase",           # 37
    "modomics",          # 38
    "vega",              # 39
    "srpdb",             # 40
    "snopy",             # 41
    "crw",               # 42
    "silva",             # 43
    "greengenes",        # 44
    "rdp",               # 45
    "ena",               # 46
    "zwd",               # 47
    "noncode",           # 48
    "evlncrnas",         # 49
    "mgnify",            # 50
]

_DB_RANK: dict[str, int] = {db: i for i, db in enumerate(DB_PRIORITY)}
_WORST = len(DB_PRIORITY)
_DB_NORMALISE: dict[str, str] = {
    "ensembl/gencode": "gencode",
    "ensembl plants": "ensembl",
    "ensembl_plants": "ensembl",
    "mouse_genome_database": "mgi",
    "hugo_gene_nomenclature_committee": "hgnc",
}

# URS IDs whose sequences exactly match an Rfam seed alignment sequence,
# generated by rfam_seed_allowlist.py. Kept regardless of the authoritative-DB pre-filter.
RFAM_SEED_ALLOWLIST: frozenset[str] = frozenset({
    # ── Homo sapiens (9606) ──
    "URS0000052456_9606", "URS0000059FA1_9606", "URS00000B0351_9606",
    "URS0000185C02_9606", "URS00001DF052_9606", "URS00001F3F45_9606",
    "URS00002CBE8B_9606", "URS00002DE03A_9606", "URS0000475C77_9606",
    "URS00004C105E_9606", "URS0000538196_9606", "URS0000584589_9606",
    "URS000058D5C7_9606", "URS00005D05D7_9606", "URS000062318B_9606",
    "URS0000623392_9606", "URS000062A6EA_9606", "URS000062C477_9606",
    "URS000062CFAD_9606", "URS0000630758_9606", "URS000064789E_9606",
    "URS0000657EA4_9606", "URS000065B202_9606", "URS000065C225_9606",
    "URS0000663EAF_9606", "URS0000664B70_9606", "URS000066AF7A_9606",
    "URS000066C0F7_9606", "URS0000675198_9606", "URS0000680F44_9606",
    "URS0000688C7B_9606", "URS0000688DFB_9606", "URS000068956C_9606",
    "URS00006898D9_9606", "URS000068AE91_9606", "URS000068AEF6_9606",
    "URS000068F4AA_9606", "URS0000699FB5_9606", "URS000069D1AA_9606",
    "URS000069DBBB_9606", "URS00006A92FA_9606", "URS00006B8DC9_9606",
    "URS00006B9362_9606", "URS00006BD38E_9606", "URS00006BE46D_9606",
    "URS00006C130C_9606", "URS00006D9320_9606", "URS00006DFBDB_9606",
    "URS00006E359A_9606", "URS00006E50D0_9606", "URS00006F859D_9606",
    "URS0000708EF5_9606", "URS000070F9D1_9606", "URS0000718DAA_9606",
    "URS000071CCC6_9606", "URS0000729E09_9606", "URS000072E78C_9606",
    "URS0000759E62_9606", "URS000075A13B_9606", "URS000075A277_9606",
    "URS000075A323_9606", "URS000075A3A6_9606", "URS000075A6D0_9606",
    "URS000075A85D_9606", "URS000075AB28_9606", "URS000075AC9B_9606",
    "URS000075B09E_9606", "URS000075B41C_9606", "URS000075C069_9606",
    "URS000075C2E3_9606", "URS000075CCA0_9606", "URS000075CE40_9606",
    "URS000075D40B_9606", "URS000075E6F6_9606", "URS000075EB8C_9606",
    "URS00007E4099_9606", "URS00007E431E_9606", "URS0000A9760C_9606",
    "URS0000A9E1B1_9606", "URS0000AA68A0_9606", "URS0000AA80DB_9606",
    "URS0000BCB2A4_9606", "URS0000BD177D_9606", "URS0000CDB53A_9606",
    "URS0000D52FF5_9606", "URS0000D56C46_9606", "URS0000E03D60_9606",
    "URS0000E87AB0_9606", "URS0001A16A6B_9606", "URS0002311E22_9606",
    "URS00023123C2_9606", "URS00023125FC_9606", "URS0002312E31_9606",
    "URS00023130A1_9606", "URS0002313284_9606", "URS0002313357_9606",
    "URS00023136AF_9606", "URS0002313758_9606", "URS0002313983_9606",
    "URS000231398E_9606", "URS0002313B10_9606", "URS0002313DAF_9606",
    "URS0002314358_9606", "URS000231447C_9606", "URS00023144EC_9606",
    "URS000231468B_9606", "URS0002314B90_9606", "URS000231556A_9606",
    "URS000231592F_9606", "URS0002315AC2_9606", "URS0002315C0A_9606",
    "URS000231699A_9606", "URS0002316A29_9606", "URS0002316E7E_9606",
    "URS0002316ED6_9606", "URS000231723C_9606", "URS00023177EE_9606",
    "URS0002317DE9_9606", "URS000231805E_9606", "URS00023180E1_9606",
    "URS0002318191_9606", "URS0002318263_9606", "URS00023182DB_9606",
    "URS00023182E9_9606", "URS0002318389_9606", "URS00023192D9_9606",
    "URS000231940B_9606", "URS0002319A59_9606", "URS0002319ADA_9606",
    "URS0002319B9D_9606", "URS0002319BE8_9606", "URS000231A092_9606",
    "URS000231A0A0_9606", "URS000231A2D0_9606", "URS000231A5B3_9606",
    "URS000231A6B9_9606", "URS000231A6CA_9606", "URS000231A7FE_9606",
    "URS000231A8CF_9606", "URS000231A901_9606", "URS000231A909_9606",
    "URS000231A996_9606", "URS000231AAF6_9606", "URS000231ABA8_9606",
    "URS000231AC69_9606", "URS000231B014_9606", "URS000231B125_9606",
    "URS000231B187_9606", "URS000231B344_9606", "URS000231B505_9606",
    "URS000231B640_9606", "URS000231B737_9606", "URS000231BC65_9606",
    "URS000231BD17_9606", "URS000231C0AC_9606", "URS000231C50B_9606",
    "URS000231C731_9606", "URS000231CE35_9606", "URS000231D059_9606",
    "URS000231D1CE_9606", "URS000231D472_9606", "URS000231D4E6_9606",
    "URS000231D59F_9606", "URS000231D7B8_9606", "URS000231DA3F_9606",
    "URS000231DCD3_9606", "URS000231DD71_9606", "URS000231E300_9606",
    "URS000231E390_9606", "URS000231E3BC_9606", "URS000231E6FC_9606",
    "URS000231E971_9606", "URS000231EBB8_9606", "URS000231EEC4_9606",
    "URS000231F3A8_9606", "URS000231F474_9606", "URS000231F5DB_9606",
    "URS000231F6FA_9606", "URS000231F9A2_9606", "URS000231FB67_9606",
    "URS000231FC63_9606", "URS000231FFC5_9606", "URS000232030B_9606",
    "URS000232037F_9606", "URS00023205B6_9606", "URS00023205FA_9606",
    "URS0002320A02_9606", "URS0002320D7C_9606", "URS0002320DC4_9606",
    "URS0002320DE1_9606", "URS0002321048_9606", "URS000232111A_9606",
    "URS00023212A2_9606", "URS0002321356_9606", "URS0002321372_9606",
    "URS0002321E21_9606", "URS0002321F26_9606", "URS0002321F38_9606",
    "URS0002321FCE_9606", "URS0002322018_9606", "URS000232203D_9606",
    "URS0002322098_9606", "URS0002322248_9606", "URS00023222FD_9606",
    "URS000232240D_9606", "URS000232242B_9606", "URS0002322458_9606",
    "URS00023224D7_9606", "URS0002322541_9606", "URS0002322714_9606",
    "URS00023229F3_9606", "URS0002322A3E_9606", "URS0002322BC9_9606",
    "URS0002322BF3_9606", "URS0002322DC4_9606", "URS0002322FA4_9606",
    "URS000232307F_9606", "URS000232370B_9606", "URS00023237ED_9606",
    "URS0002323832_9606", "URS0002323936_9606", "URS00023239BA_9606",
    "URS0002323AD3_9606", "URS0002323B06_9606", "URS0002323CF4_9606",
    "URS0002323D65_9606", "URS0002323F15_9606", "URS0002323F7A_9606",
    "URS00023240C5_9606", "URS0002324368_9606", "URS0002324403_9606",
    "URS0002324583_9606", "URS000232469D_9606", "URS00023250B5_9606",
    "URS00023250E3_9606", "URS00023254C2_9606", "URS00023255A8_9606",
    "URS0002325615_9606", "URS0002325F93_9606", "URS000232600D_9606",
    "URS0002326139_9606", "URS0002327628_9606", "URS0002327764_9606",
    "URS00023277CD_9606", "URS0002327837_9606", "URS0002327CAB_9606",
    "URS0002327DAE_9606", "URS0002327E3F_9606", "URS0002327EEC_9606",
    "URS00023281D5_9606", "URS0002328528_9606", "URS00023285A1_9606",
    "URS000232879C_9606", "URS0002328A92_9606", "URS0002328C3C_9606",
    "URS0002328FBD_9606", "URS00023291E3_9606", "URS00023292F5_9606",
    "URS0002329445_9606", "URS000232975C_9606", "URS00023299E6_9606",
    "URS0002329A4F_9606", "URS0002329E36_9606", "URS0002329E46_9606",
    "URS000232A2C3_9606", "URS000232A5D3_9606", "URS000232AA0F_9606",
    "URS000232ACC7_9606", "URS000232ACD7_9606", "URS000232B08B_9606",
    "URS000232B1B6_9606", "URS000232B1EE_9606", "URS000232B534_9606",
    "URS000232B8F9_9606", "URS000232BA98_9606", "URS000232BC6B_9606",
    "URS000232BC9D_9606", "URS000232BFBE_9606", "URS000232BFEE_9606",
    "URS000232C103_9606", "URS000232C166_9606", "URS000232C374_9606",
    "URS000232C378_9606", "URS000232C5C9_9606", "URS000232CAA8_9606",
    "URS000232CE9D_9606", "URS000232CFEE_9606", "URS000232D1D3_9606",
    "URS000232D69A_9606", "URS000232D721_9606", "URS000232D845_9606",
    "URS000232DA88_9606", "URS000232DB9D_9606", "URS000232E00D_9606",
    "URS000232E153_9606", "URS000232E286_9606", "URS000232E62B_9606",
    "URS000232E7DD_9606", "URS000232EC02_9606", "URS000232EE0D_9606",
    "URS000232F71A_9606", "URS000232F795_9606", "URS000232F83A_9606",
    "URS000232F8F0_9606", "URS000232F988_9606", "URS000232FA8A_9606",
    "URS000232FAE2_9606", "URS000232FB78_9606", "URS000232FBD3_9606",
    "URS000232FD2C_9606", "URS000232FEF0_9606", "URS0002330372_9606",
    "URS000233037C_9606", "URS000233048D_9606", "URS00023304A9_9606",
    "URS000233066A_9606", "URS0002330A76_9606", "URS0002330A7D_9606",
    "URS0002330AB3_9606", "URS0002330DC1_9606", "URS0002330DF9_9606",
    "URS00023311B7_9606", "URS00023312EE_9606", "URS0002332247_9606",
    "URS000233227B_9606", "URS000233264E_9606", "URS00023326FA_9606",
    "URS0002332DE6_9606", "URS00023331B5_9606", "URS0002333825_9606",
    "URS0002333929_9606", "URS00023339A1_9606", "URS0002333AD6_9606",
    "URS0002333BFC_9606", "URS0002333F72_9606", "URS00023340A8_9606",
    "URS00023340CA_9606", "URS000233477B_9606", "URS0002334DF7_9606",
    "URS0002335424_9606", "URS0002335512_9606", "URS0002616BC5_9606",
    "URS0002616C39_9606", "URS0002616C78_9606", "URS0002616CDF_9606",
    "URS0002616EA4_9606", "URS0002616ECD_9606", "URS0002617061_9606",
    "URS00026170D3_9606", "URS0002617176_9606", "URS0002617248_9606",
    "URS00026173E5_9606", "URS0002617488_9606", "URS00026175A0_9606",
    "URS00026175E1_9606", "URS00026175F4_9606", "URS00027DC61C_9606",
    "URS00027DDF00_9606", "URS00027DE7CA_9606", "URS00027DF7BC_9606",
    "URS00027DF85B_9606", "URS00027DFB7E_9606", "URS00027E034D_9606",
    "URS00027E15BE_9606", "URS00029108D8_9606", "URS000291095C_9606",
    "URS00029109F0_9606", "URS0002910B0F_9606", "URS0002910BA0_9606",
    "URS0002910BB9_9606", "URS0002910D08_9606", "URS0002910F60_9606",
    "URS000291103E_9606", "URS00029110EF_9606", "URS0002911202_9606",
    "URS0002911340_9606", "URS000291144C_9606", "URS0002911480_9606",
    "URS00029114D9_9606", "URS00029115CB_9606", "URS0002911A42_9606",
    "URS0002911AD8_9606", "URS0002911BC3_9606", "URS0002911D79_9606",
    "URS0002911DD0_9606", "URS0002911E45_9606", "URS0002911EF7_9606",
    "URS0002912139_9606", "URS000291221E_9606", "URS0002912224_9606",
    "URS000291222C_9606", "URS000291223A_9606", "URS00029122DF_9606",
    "URS0002912339_9606", "URS00029123B3_9606", "URS00029123CF_9606",
    "URS0002912415_9606", "URS0002912459_9606", "URS000291249F_9606",
    "URS0002912574_9606", "URS0002912657_9606", "URS00029126DF_9606",
    "URS0002912706_9606", "URS000291283D_9606", "URS000291294E_9606",
    "URS0002912B1F_9606", "URS0002912B66_9606", "URS0002912C61_9606",
    "URS0002912CFE_9606", "URS0002912DFE_9606", "URS0002912E1C_9606",
    "URS0002912E6A_9606", "URS0002912EB5_9606", "URS00029131AE_9606",
    "URS000291321B_9606", "URS0002913292_9606", "URS00029132EC_9606",
    "URS0002913359_9606", "URS0002913362_9606", "URS0002913490_9606",
    "URS00029134C0_9606", "URS00029134F8_9606", "URS0002913578_9606",
    "URS00029138A2_9606", "URS00029138D6_9606", "URS00029138DA_9606",
    "URS000291390B_9606", "URS0002913A5C_9606", "URS0002913ADD_9606",
    "URS0002913BD4_9606", "URS0002913EF0_9606", "URS0002913EFC_9606",
    "URS000291409F_9606", "URS00029141C2_9606", "URS0002914305_9606",
    "URS0002914341_9606", "URS0002914376_9606", "URS0002914402_9606",
    "URS0002914458_9606", "URS0002914485_9606", "URS0002914553_9606",
    "URS0002914582_9606", "URS0002914588_9606", "URS00029145C1_9606",
    "URS00029146D9_9606", "URS0002914771_9606", "URS00029147A7_9606",
    "URS0002914CFF_9606", "URS0002914D23_9606", "URS0002914EB1_9606",
    "URS0002915188_9606", "URS0002915357_9606", "URS0002915418_9606",
    "URS00029154D9_9606", "URS0002915561_9606", "URS00029155A2_9606",
    "URS000305E541_9606", "URS000306F63A_9606", "URS0003075071_9606",
    "URS000307512B_9606", "URS0003081415_9606", "URS000308FE43_9606",
    "URS00030951CC_9606", "URS00030A0E08_9606", "URS00030AEE9E_9606",
    "URS00030C0029_9606", "URS00030C3974_9606", "URS00030C8E47_9606",
    "URS00030DF3DB_9606", "URS00030E0F7A_9606", "URS00030E6092_9606",
    "URS00030F2338_9606", "URS00030FC625_9606", "URS000312A5E6_9606",
    "URS000313441C_9606", "URS000313BE0B_9606", "URS0003154445_9606",
    "URS0003179F60_9606", "URS0003180E55_9606", "URS0003188BAF_9606",
    "URS0003189486_9606", "URS000319BA8E_9606", "URS00031B9D27_9606",
    "URS00031C67AE_9606", "URS00031DB251_9606", "URS00031E8951_9606",
    "URS0003206063_9606", "URS000327A727_9606", "URS000327A93A_9606",
    "URS00032A913F_9606", "URS00032B0168_9606", "URS00032B17A1_9606",
    "URS00032B79CF_9606", "URS00032D215A_9606", "URS0003304147_9606",
    "URS0003306D6D_9606", "URS0003342F4C_9606", "URS0003346DB8_9606",
    "URS00033501BE_9606", "URS000336AEF4_9606", "URS000336DAE1_9606",
    "URS000339A494_9606", "URS000339F24A_9606", "URS00033AA843_9606",
    "URS00033BBB20_9606", "URS00033FC7D5_9606", "URS000001388A_9606",
    "URS000005CCC5_9606", "URS000005DEC4_9606", "URS000007BC04_9606",
    "URS000011C781_9606", "URS0000134CEC_9606", "URS0000174BD8_9606",
    "URS0000196107_9606", "URS0000205DCB_9606", "URS000020E7DF_9606",
    "URS0000295DAE_9606", "URS00002DBC68_9606", "URS000031F4C1_9606",
    "URS00003F0D62_9606", "URS0000428A90_9606", "URS0000489790_9606",
    "URS00004C170A_9606", "URS00004C8BCF_9606", "URS000056438E_9606",
    "URS000056AA63_9606", "URS00005810E4_9606", "URS0000583A29_9606",
    "URS00005CE4DD_9606", "URS000062882C_9606", "URS000062A977_9606",
    "URS000062BAD5_9606", "URS000062E1B3_9606", "URS0000637FD6_9606",
    "URS0000638663_9606", "URS0000644C65_9606", "URS000064F3A2_9606",
    "URS000065655A_9606", "URS000065A565_9606", "URS0000668E72_9606",
    "URS000067D064_9606", "URS00006A2AF1_9606", "URS00006ABB7D_9606",
    "URS00006AE0E6_9606", "URS00006B2AE2_9606", "URS00006C0C10_9606",
    "URS00006C61E2_9606", "URS00006CF1CC_9606", "URS00006D744B_9606",
    "URS00006E374E_9606", "URS00006E6CBD_9606", "URS00006EC6A3_9606",
    "URS000072497E_9606", "URS0000725D77_9606", "URS0000C0DBD4_9606",
    "URS0000C84B1A_9606", "URS0002312E5F_9606", "URS00023150F0_9606",
    "URS0002315B0F_9606", "URS0002317470_9606", "URS0002319D0C_9606",
    "URS000231AEC9_9606", "URS000231C493_9606", "URS000231D0C4_9606",
    "URS000231DA17_9606", "URS000231DB0D_9606", "URS000231F151_9606",
    "URS0002320628_9606", "URS00023207F4_9606", "URS00023227D6_9606",
    "URS000232424B_9606", "URS0002325E64_9606", "URS0002326275_9606",
    "URS0002327C43_9606", "URS00023281A3_9606", "URS0002329E8F_9606",
    "URS000232A742_9606", "URS000232B2B4_9606", "URS000232BE34_9606",
    "URS000232D2F5_9606", "URS000232DBE6_9606", "URS000232F904_9606",
    "URS0002332BD8_9606", "URS0002334C76_9606", "URS0000672FFD_9606",
    "URS000069D029_9606", "URS00006AF1DC_9606", "URS00006BD80C_9606",
    "URS00006DA4DE_9606", "URS00007206BB_9606", "URS00003516B6_9606",
    "URS00004E86FE_9606", "URS00006020B7_9606", "URS00006F0FC0_9606",
    "URS000073556F_9606", "URS0000679FDD_9606", "URS000231EE2E_9606",
    "URS000232B21F_9606", "URS000069466F_9606", "URS0000A8FF41_9606",
    "URS0002316A23_9606", "URS00006825AD_9606", "URS00006A4CA5_9606",
    "URS0000707BE6_9606",
    # ── Mus musculus (10090) ──
    "URS0000052456_10090", "URS00000CA97A_10090", "URS000016B83E_10090",
    "URS00001DF052_10090", "URS00002DE03A_10090", "URS0000538196_10090",
    "URS0000561D92_10090", "URS00005D05D7_10090", "URS0000622AAE_10090",
    "URS00006238FE_10090", "URS0000628B8E_10090", "URS0000641524_10090",
    "URS000064ACAD_10090", "URS000064BB84_10090", "URS00006581B8_10090",
    "URS000066667F_10090", "URS0000668C03_10090", "URS000066B802_10090",
    "URS0000675198_10090", "URS000067AC25_10090", "URS000067D11A_10090",
    "URS0000684766_10090", "URS00006849F0_10090", "URS0000688CFC_10090",
    "URS000068AEF6_10090", "URS000068B25D_10090", "URS00006918DC_10090",
    "URS00006974D2_10090", "URS000069A106_10090", "URS00006A186B_10090",
    "URS00006A459C_10090", "URS00006A5C49_10090", "URS00006AE8B7_10090",
    "URS00006B1F90_10090", "URS00006BEA73_10090", "URS00006C130C_10090",
    "URS00006C4C11_10090", "URS00006DB1F6_10090", "URS00006E7572_10090",
    "URS00006EE6A2_10090", "URS00006F3DA4_10090", "URS00006FC24B_10090",
    "URS00007078D8_10090", "URS000070A416_10090", "URS0000711B95_10090",
    "URS00007156EA_10090", "URS000071BD6A_10090", "URS0000759B42_10090",
    "URS000075A956_10090", "URS000075B09E_10090", "URS000075CE40_10090",
    "URS000075D137_10090", "URS000075D8CA_10090", "URS000075E0E9_10090",
    "URS000075E9FD_10090", "URS00007E3FFA_10090", "URS00007E431E_10090",
    "URS0000DF89BC_10090", "URS0002311ACB_10090", "URS0002311C1E_10090",
    "URS000231256F_10090", "URS000231269F_10090", "URS00023134CC_10090",
    "URS00023137BF_10090", "URS000231398E_10090", "URS0002313CEB_10090",
    "URS0002313DE7_10090", "URS000231441C_10090", "URS000231459E_10090",
    "URS00023148EC_10090", "URS0002314A53_10090", "URS000231504E_10090",
    "URS0002315106_10090", "URS0002315535_10090", "URS0002315B6D_10090",
    "URS0002315E6E_10090", "URS0002316177_10090", "URS0002316681_10090",
    "URS00023170C2_10090", "URS0002317A11_10090", "URS0002317C12_10090",
    "URS0002317F9B_10090", "URS00023184BD_10090", "URS00023184D3_10090",
    "URS0002318704_10090", "URS0002318DAA_10090", "URS0002319507_10090",
    "URS0002319F2D_10090", "URS000231A005_10090", "URS000231A6F4_10090",
    "URS000231A728_10090", "URS000231AD21_10090", "URS000231B187_10090",
    "URS000231B6A9_10090", "URS000231B78F_10090", "URS000231B79A_10090",
    "URS000231BFA2_10090", "URS000231C997_10090", "URS000231CA33_10090",
    "URS000231CD04_10090", "URS000231CE35_10090", "URS000231CF94_10090",
    "URS000231D136_10090", "URS000231D168_10090", "URS000231DBE8_10090",
    "URS000231DCD3_10090", "URS000231DEEF_10090", "URS000231E2AF_10090",
    "URS000231E42E_10090", "URS000231EE01_10090", "URS000231F5DB_10090",
    "URS000231FAB4_10090", "URS00023205E0_10090", "URS0002320B92_10090",
    "URS0002320BEF_10090", "URS0002321374_10090", "URS0002321625_10090",
    "URS0002321DE6_10090", "URS0002321EB3_10090", "URS00023225E6_10090",
    "URS0002322B48_10090", "URS0002322C3F_10090", "URS0002323D74_10090",
    "URS0002323F40_10090", "URS0002324DFF_10090", "URS0002325265_10090",
    "URS00023268CF_10090", "URS0002326F77_10090", "URS0002327818_10090",
    "URS0002328011_10090", "URS0002329F10_10090", "URS000232A3BD_10090",
    "URS000232A6E1_10090", "URS000232ADD5_10090", "URS000232B08B_10090",
    "URS000232B1C9_10090", "URS000232B9A7_10090", "URS000232BB48_10090",
    "URS000232BD77_10090", "URS000232C1DD_10090", "URS000232CB54_10090",
    "URS000232CCBC_10090", "URS000232D893_10090", "URS000232D8A9_10090",
    "URS000232DFBB_10090", "URS000232E0DF_10090", "URS000232E62B_10090",
    "URS000232EC02_10090", "URS000232EE02_10090", "URS000232EFBE_10090",
    "URS000232F479_10090", "URS000232F49D_10090", "URS000232F78C_10090",
    "URS000232F966_10090", "URS000232FB78_10090", "URS000232FF5D_10090",
    "URS00023300D6_10090", "URS000233043C_10090", "URS0002330777_10090",
    "URS00023309E2_10090", "URS000233150B_10090", "URS0002331851_10090",
    "URS0002331898_10090", "URS0002331A69_10090", "URS0002331C13_10090",
    "URS000233209D_10090", "URS00023337A9_10090", "URS0002333B46_10090",
    "URS0002333E1B_10090", "URS0002616C0C_10090", "URS0002616C1A_10090",
    "URS0002616D54_10090", "URS0002616D63_10090", "URS0002616DEB_10090",
    "URS0002616E52_10090", "URS000261704C_10090", "URS00026171CD_10090",
    "URS00026173C8_10090", "URS0002617452_10090", "URS0002617508_10090",
    "URS0002617570_10090", "URS00026175C8_10090", "URS0002617677_10090",
    "URS00027DEE8B_10090", "URS00027E0A77_10090", "URS00027E0B1A_10090",
    "URS00027E1616_10090", "URS00027E1B55_10090", "URS00027E2EE8_10090",
    "URS00027E2F65_10090", "URS00029108D7_10090", "URS0002910930_10090",
    "URS000291094F_10090", "URS00029109F2_10090", "URS0002910C34_10090",
    "URS0002910C51_10090", "URS0002910D75_10090", "URS0002910E32_10090",
    "URS0002910E79_10090", "URS0002910F91_10090", "URS0002911053_10090",
    "URS000291109D_10090", "URS00029111D7_10090", "URS00029111F1_10090",
    "URS000291123D_10090", "URS00029115FE_10090", "URS00029117C1_10090",
    "URS00029117C8_10090", "URS0002911906_10090", "URS0002911BC3_10090",
    "URS0002911C66_10090", "URS0002911EA7_10090", "URS0002911EA8_10090",
    "URS0002911EBE_10090", "URS0002911EEF_10090", "URS0002911F03_10090",
    "URS00029121A7_10090", "URS0002912339_10090", "URS00029126DD_10090",
    "URS0002912859_10090", "URS0002912886_10090", "URS000291293A_10090",
    "URS000291298E_10090", "URS00029129DD_10090", "URS0002912F54_10090",
    "URS0002913163_10090", "URS00029132B5_10090", "URS000291346F_10090",
    "URS000291361D_10090", "URS0002913713_10090", "URS00029138A6_10090",
    "URS0002913A52_10090", "URS0002913B59_10090", "URS0002913C32_10090",
    "URS0002914019_10090", "URS00029143F2_10090", "URS0002914436_10090",
    "URS000291460D_10090", "URS00029147C5_10090", "URS0002914801_10090",
    "URS00029148D2_10090", "URS0002914944_10090", "URS00029149F8_10090",
    "URS0002914B94_10090", "URS0002914C15_10090", "URS0002914D62_10090",
    "URS0002914EF0_10090", "URS0002914F9D_10090", "URS00029150A0_10090",
    "URS00030780DA_10090", "URS0003081415_10090", "URS00030951CC_10090",
    "URS00030A2262_10090", "URS00030BBCD0_10090", "URS00030DAC73_10090",
    "URS00030F302C_10090", "URS000311248B_10090", "URS000314BB59_10090",
    "URS00031772B0_10090", "URS0003179F60_10090", "URS000319A8F1_10090",
    "URS00031C67AE_10090", "URS00031CBBEE_10090", "URS00031DB251_10090",
    "URS00031E6507_10090", "URS00031E8951_10090", "URS00031F74ED_10090",
    "URS00031F8628_10090", "URS000320587A_10090", "URS000323B99D_10090",
    "URS0003244342_10090", "URS0003264361_10090", "URS000327A727_10090",
    "URS000327A93A_10090", "URS00032A1CE5_10090", "URS00032A913F_10090",
    "URS00032B0168_10090", "URS00032B17A1_10090", "URS00032B79CF_10090",
    "URS00032BB206_10090", "URS00032C82F4_10090", "URS00032F58C6_10090",
    "URS0003306D6D_10090", "URS0003344C11_10090", "URS0003348BA9_10090",
    "URS000339A494_10090", "URS000339F24A_10090", "URS00033BBB20_10090",
    "URS00033DDF0D_10090", "URS00033FC7D5_10090", "URS000000E482_10090",
    "URS000002A848_10090", "URS0000060CC3_10090", "URS000008A8DA_10090",
    "URS00000C104F_10090", "URS00000F74F3_10090", "URS0000129B3E_10090",
    "URS00001BD500_10090", "URS00001C7469_10090", "URS00002052CD_10090",
    "URS000025413C_10090", "URS00002B5748_10090", "URS00002F2563_10090",
    "URS00003A3A32_10090", "URS00003B1562_10090", "URS00003B9E15_10090",
    "URS00003EDAB4_10090", "URS00003F2612_10090", "URS000043D29D_10090",
    "URS000043FC73_10090", "URS000044282B_10090", "URS000048F194_10090",
    "URS00004A7C5C_10090", "URS00004CABA3_10090", "URS00004F9942_10090",
    "URS000051591B_10090", "URS000051DCEC_10090", "URS000051FAC8_10090",
    "URS000053E02C_10090", "URS000058BC96_10090", "URS00005C4842_10090",
    "URS00005EF12F_10090", "URS00006026BA_10090", "URS000060B496_10090",
    "URS0000610280_10090", "URS0000632B88_10090", "URS00006413A0_10090",
    "URS0000652DC1_10090", "URS0000663E79_10090", "URS0000675BC6_10090",
    "URS000067BE1E_10090", "URS0000682F13_10090", "URS0000687706_10090",
    "URS000068C0D7_10090", "URS00006A3EAC_10090", "URS00006A6584_10090",
    "URS00006A65BA_10090", "URS00006CF195_10090", "URS00006D884C_10090",
    "URS00006DDAEA_10090", "URS00006F9FD6_10090", "URS0000707B6B_10090",
    "URS0000710AB7_10090", "URS000071930A_10090", "URS0000729E5D_10090",
    "URS000075E48F_10090", "URS0000BE220F_10090", "URS0002312AAE_10090",
    "URS00023148D0_10090", "URS0002319049_10090", "URS000231AC02_10090",
    "URS000231B0D8_10090", "URS000231B69A_10090", "URS000231BF66_10090",
    "URS000231EE29_10090", "URS0002324B75_10090", "URS0002324C85_10090",
    "URS0002325A5D_10090", "URS0002326333_10090", "URS00023297BA_10090",
    "URS00023299B4_10090", "URS000232ABC4_10090", "URS000232AC2C_10090",
    "URS000232BEFF_10090", "URS000232CC6E_10090", "URS000232CF11_10090",
    "URS000232E210_10090", "URS000232E21E_10090", "URS000232F0DA_10090",
    "URS000004D412_10090", "URS00003F3C4B_10090", "URS0000609F0B_10090",
    "URS000069E761_10090", "URS000231C2C5_10090", "URS000231CC24_10090",
    "URS000232781E_10090", "URS00001818B2_10090", "URS000042C8C2_10090",
    "URS000047A816_10090", "URS0000624339_10090", "URS00000EF58B_10090",
    "URS0002314F20_10090", "URS0002316A41_10090", "URS00006AFC6A_10090",
    "URS00023228E4_10090",
})

# Numbered or roman-numeral chromosomes plus sex/organelle names; drops unplaced scaffolds.
_PRIMARY_CHROM = re.compile(r"\d+|[IVX]+|X|Y|MT|Mito|Mt|Pt")

# Transcripts more than this factor longer than the shortest in a cluster
# are placed in a separate length group, allowing both to be represented.
LENGTH_RATIO_THRESHOLD = 2.0


# Databases that vouch for a biotype; transcripts lacking one are dropped by the pre-filter.
AUTHORITATIVE_DBS: dict[str, frozenset[str]] = {
    "miRNA":     frozenset({"mirbase", "mirgenedb"}),
    "pre_miRNA": frozenset({"mirbase", "mirgenedb", "ensembl", "gencode"}),
    "rRNA":      frozenset({"silva", "ensembl", "refseq", "crw", "ribocentredb", "5srrnadb", "pdbe"}),
    "tRNA":      frozenset({"gtrnadb", "ensembl", "gencode"}),
    "piRNA":     frozenset({"pirbase"}),
    "SRP_RNA":   frozenset({"srpdb", "ensembl", "gencode"}),
    "snRNA":     frozenset({"ensembl", "gencode", "refseq", "rfam", "pdbe"}),
    "snoRNA":    frozenset({"snodb", "snopy", "ensembl", "gencode"}),
    "scaRNA":    frozenset({"ensembl", "gencode"}),
    "Y_RNA":     frozenset({"ensembl", "gencode", "refseq"}),
    "lncRNA":    frozenset({"ensembl", "gencode", "lncipedia", "lncbook", "lncrnadb", "refseq"}),
    "misc_RNA":  frozenset({"ensembl", "gencode", "refseq", "pdbe"}),
    "sRNA":      frozenset({"ensembl", "gencode", "refseq"}),
}


def has_authoritative_db(databases: str, biotype: str) -> bool:
    if biotype not in AUTHORITATIVE_DBS:
        return True
    dbs = set()
    for d in databases.split(","):
        key = d.strip().lower()
        dbs.add(_DB_NORMALISE.get(key, key))
    return bool(dbs & AUTHORITATIVE_DBS[biotype])


def _best_rank(field: str) -> int:
    if not field:
        return _WORST
    best = _WORST
    for db in field.split(","):
        key = db.strip().lower()
        key = _DB_NORMALISE.get(key, key)
        best = min(best, _DB_RANK.get(key, _WORST))
    return best


def _unique_count(field: str) -> int:
    if not field:
        return 0
    return len({d.strip().lower() for d in field.split(",")})


def _parse_attrs(attr_str: str) -> dict[str, str]:
    attrs: dict[str, str] = {}
    for part in attr_str.split(";"):
        part = part.strip()
        if "=" in part:
            k, v = part.split("=", 1)
            attrs[k] = v
    return attrs


def _open(path: str, mode: str = "rt"):
    if path.endswith(".gz"):
        return gzip.open(path, mode, encoding="utf-8" if "t" in mode else None)
    return open(path, mode, encoding="utf-8" if "t" in mode else None)


def _overlap_clusters(txs: list) -> list[list]:
    txs = sorted(txs, key=lambda x: (x["start"], x["end"]))
    clusters: list[list] = []
    current: list = []
    end = -1
    for tx in txs:
        if current and tx["start"] > end:
            clusters.append(current)
            current = []
            end = -1
        current.append(tx)
        end = max(end, tx["end"])
    if current:
        clusters.append(current)
    return clusters


def _length_groups(txs: list) -> list[list]:
    """Partition transcripts into similar-length groups (ratio <= LENGTH_RATIO_THRESHOLD)."""
    sorted_txs = sorted(txs, key=lambda x: x["end"] - x["start"])
    groups: list[list] = []
    current: list = []
    anchor_len: int = 0
    for tx in sorted_txs:
        tx_len = tx["end"] - tx["start"]
        if not current:
            current.append(tx)
            anchor_len = tx_len
        elif anchor_len == 0 or tx_len / anchor_len <= LENGTH_RATIO_THRESHOLD:
            current.append(tx)
        else:
            groups.append(current)
            current = [tx]
            anchor_len = tx_len
    if current:
        groups.append(current)
    return groups


def _predicted_gene_groups(txs: list, predicted_gene_ids: set[str]) -> list[list]:
    recognised: dict[str, list] = defaultdict(list)
    other:      dict[str, list] = defaultdict(list)
    no_parent:  list             = []

    for tx in txs:
        parent = tx["parent"]
        if parent in predicted_gene_ids:
            recognised[parent].append(tx)
        elif parent:
            other[parent].append(tx)
        else:
            no_parent.append(tx)

    if recognised or other:
        groups  = [recognised[p] for p in sorted(recognised)]
        groups += [other[p]      for p in sorted(other)]
        return groups      # parentless transcripts dropped when predicted_gene-backed ones exist
    return [txs]


def _effective_rank(t: dict) -> int:
    if t["prov_rank"] < _WORST:
        return t["prov_rank"]
    return _best_rank(t["databases"])


def main() -> None:
    """Run the two-stage GFF3 filter and write the result."""
    argv = sys.argv[1:]
    no_prefilter = "--no-prefilter" in argv
    pirna_max_loci = int(argv[argv.index("--pirna-max-loci") + 1]) if "--pirna-max-loci" in argv else None
    args = [a for i, a in enumerate(argv)
            if not a.startswith("--") and (i == 0 or argv[i - 1] != "--pirna-max-loci")]
    if len(args) < 2:
        print(f"Usage: {sys.argv[0]} [--no-prefilter] [--pirna-max-loci N] input.gff3[.gz] output.gff3[.gz]",
              file=sys.stderr)
        sys.exit(1)

    in_path, out_path = args[0], args[1]

    # ── Pass 1: collect transcript and predicted-gene metadata ───────────────
    print("Pass 1: reading transcripts and predicted genes …", file=sys.stderr)
    transcripts: dict[str, dict] = {}
    predicted_gene_ids: set[str] = set()
    circ_dropped = 0

    with _open(in_path) as fh:
        for line in fh:
            if line.startswith("#"):
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 9:
                continue
            chrom, _, feature, start, end, _, strand, _, attrs_str = parts
            if not _PRIMARY_CHROM.fullmatch(chrom):
                continue
            attrs     = _parse_attrs(attrs_str)
            if feature == "predicted_gene":
                gid = attrs.get("ID", "")
                if gid:
                    predicted_gene_ids.add(gid)
                continue
            if feature != "transcript":
                continue
            if attrs.get("type", "") == "circRNA":
                circ_dropped += 1
                continue
            tid       = attrs.get("ID", "")
            if not tid:
                continue
            prov      = attrs.get("providing_databases", "")
            databases = attrs.get("databases", "")
            transcripts[tid] = {
                "chrom":      chrom,
                "start":      int(start),
                "end":        int(end),
                "strand":     strand,
                "type":       attrs.get("type", ""),
                "name":       attrs.get("Name", ""),
                "prov":       prov,
                "databases":  databases,
                "prov_rank":  _best_rank(prov),
                "prov_count": _unique_count(prov),
                "db_count":   _unique_count(databases),
                "parent":     attrs.get("Parent", ""),
                "id":         tid,
            }

    print(f"  {len(transcripts):,} transcripts found "
          f"({circ_dropped:,} circRNA dropped)", file=sys.stderr)
    print(f"  {len(predicted_gene_ids):,} predicted genes found", file=sys.stderr)

    if pirna_max_loci is not None:
        loci_per_pirna: dict[str, int] = defaultdict(int)
        for t in transcripts.values():
            if t["type"] == "piRNA":
                loci_per_pirna[t["name"]] += 1
        before = len(transcripts)
        transcripts = {
            tid: t for tid, t in transcripts.items()
            if loci_per_pirna.get(t["name"], 0) <= pirna_max_loci
        }
        print(f"  {before - len(transcripts):,} piRNA entries dropped "
              f"(sequences at >{pirna_max_loci} loci)", file=sys.stderr)

    # ── Pre-filter: require authoritative database per biotype ────────────────
    before_pre = len(transcripts)
    transcripts = {
        tid: t for tid, t in transcripts.items()
        if no_prefilter or t["name"] in RFAM_SEED_ALLOWLIST or has_authoritative_db(t["databases"], t["type"])
    }
    allowlist_kept = sum(1 for t in transcripts.values() if t["name"] in RFAM_SEED_ALLOWLIST)
    print(f"Pre-filter: removed {before_pre - len(transcripts):,} lacking authoritative DB "
          f"({len(transcripts):,} remaining, {allowlist_kept:,} kept via Rfam seed allowlist)",
          file=sys.stderr)

    # ── Stage 1: collapse same-URS duplicates ────────────────────────────────
    print("Stage 1: collapsing same-URS duplicates …", file=sys.stderr)

    by_name: dict[str, list] = defaultdict(list)
    for t in transcripts.values():
        by_name[t["name"]].append(t)

    stage1_kept: set[str] = set()
    for txs in by_name.values():
        for cluster in _overlap_clusters(txs):
            best = min(cluster, key=lambda x: (
                x["prov_rank"],
                -x["prov_count"],
                -(x["end"] - x["start"]),
                x["id"],
            ))
            stage1_kept.add(best["id"])

    removed1 = len(transcripts) - len(stage1_kept)
    pct1 = removed1 / len(transcripts) * 100 if transcripts else 0
    print(f"  {len(stage1_kept):,} kept, {removed1:,} removed ({pct1:.1f}%)",
          file=sys.stderr)
    # ── Stage 2: length-aware + predicted-gene-aware locus filtering ────────────
    # Partition each overlap cluster into length groups (2x ratio), then within
    # each length group apply predicted-gene-aware selection.  This ensures that
    # transcripts much longer than their neighbours are not silently dropped just
    # because a shorter predicted-gene-backed entry exists at the same locus.
    print("Stage 2: length-aware + predicted-gene-aware locus filtering …",
          file=sys.stderr)

    loci: dict[tuple, list] = defaultdict(list)
    for tid in stage1_kept:
        t = transcripts[tid]
        loci[(t["chrom"], t["strand"], t["type"])].append(t)

    stage2_kept: set[str] = set()
    for txs in loci.values():
        for cluster in _overlap_clusters(txs):
            for length_group in _length_groups(cluster):
                for group in _predicted_gene_groups(length_group, predicted_gene_ids):
                    best = min(group, key=lambda x: (
                        _effective_rank(x),
                        -x["db_count"],
                        -(x["end"] - x["start"]),
                        x["id"],
                    ))
                    stage2_kept.add(best["id"])

    removed2 = len(stage1_kept) - len(stage2_kept)
    pct2 = removed2 / len(stage1_kept) * 100 if stage1_kept else 0
    print(f"  {len(stage2_kept):,} kept, {removed2:,} removed ({pct2:.1f}%)",
          file=sys.stderr)
    kept_parents = {transcripts[tid]["parent"]
                    for tid in stage2_kept
                    if transcripts[tid]["parent"]}

    # ── Pass 2: stream-filter and write ──────────────────────────────────────
    print("Pass 2: writing filtered GFF3 …", file=sys.stderr)
    written = 0

    with _open(in_path) as fh, _open(out_path, "wt") as out:
        for line in fh:
            if line.startswith("#"):
                out.write(line)
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 9:
                continue
            feature   = parts[2]
            attrs_str = parts[8]
            attrs     = _parse_attrs(attrs_str)

            if feature == "transcript":
                if attrs.get("ID", "") in stage2_kept:
                    out.write(line)
                    written += 1
            elif feature == "noncoding_exon":
                if attrs.get("Parent", "") in stage2_kept:
                    out.write(line)
                    written += 1
            elif feature == "predicted_gene":
                if attrs.get("ID", "") in kept_parents:
                    out.write(line)
                    written += 1

    print(f"  {written:,} feature lines written", file=sys.stderr)
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()

